[green_agent]
agentbeats_id = "019bc5a5-6acd-70e1-ae07-e6b70dea9655"
env = {OPENAI_API_KEY = "${OPENAI_API_KEY}"}

[[participants]]
agentbeats_id = ""
name = "purple_baseline"
env = {}
 
[config]
num_tasks = 167
subjects = ["web", "science"]
difficulty = ["easy", "medium", "hard", "expert"]
seed = 42 
